version: 2
updates:
  # NPM Dependencies
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'deps'
    open-pull-requests-limit: 5
