name: CI Check

# Trigger der Pipeline
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  # Einfacher Check ob alles funktioniert
  check:
    runs-on: ubuntu-latest

    steps:
      # Repository auschecken
      - name: Checkout code
        uses: actions/checkout@v4

      # Node.js setup
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      # Dependencies installieren
      - name: Install dependencies
        run: npm ci

      # Type checking
      - name: Type check
        run: npm run type-check

      # Linting
      - name: Run ESLint
        run: npm run lint

      # Tests ausführen
      - name: Run tests
        run: npm run test:unit

      # Build erstellen (prüft ob Build funktioniert)
      - name: Build application
        run: npm run build
